### ISSUE TITLE
Rescue time activities

### ISSUE THREAD

**Issue by joshsalvi** [c99koder/personal-influxdb#23]
Hello

the rescue time dashboard is only displaying ${_cell2} (not exact) in the dashboard from the JSON in the repo. Is there a fix for this? Happy to share screenshots!

thanks again!!

**Comment by c99koder** [comment]
I've updated the Rescuetime JSON to work with newer versions of Grafana. The other dashboards will most likely need an update too.  Here's what I had to change:

1. Migrated tables to the newer Table panel
2. Changed query to return a time series instead of a table
3. Add a `Concatenate fields` transform to merge the columns into a single frame
4. Adjust the column formatting overrides to use the new column names
